### ISSUE TITLE
Catchable fatal error: Argument 1 passed to Spot\Mapper::__construct()

### ISSUE THREAD

**Issue by flik** [spotorm/spot2#212]
I have a table scrapped in my database. 

$spot = new \Spot\Mapper();
$tableMapper = $spot->mapper('Entity\Scrapped');
var_dump($tableMapper);

Catchable fatal error: Argument 1 passed to Spot\Mapper::__construct() must be an instance of Spot\Locator, none given, called in C:\xampp\htdocs\scrapped\index.php on line 24 and defined in C:\xampp\htdocs\scrapped\vendor\vlucas\spot2\lib\Mapper.php on line 33

**Comment by FlipEverything** [comment]
I have to say that you're doing it wrong. That's not how spot works.
You can find everything about the first steps of using spot on the website:

Step 1. http://phpdatamapper.com/docs/database-setup/
Step 2. http://phpdatamapper.com/docs/mappers/
Step 3. http://phpdatamapper.com/docs/entities/
Step 4. http://phpdatamapper.com/docs/crud/

Have a nice day! If your issue is resolved please close it.
