### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by marcelloh** [spotorm/spot2#214]
So I deleted my composer dir and updated all my vendors.
But now I have an outdated spot-orm.
Is misses the mapper::exec()

**Comment by FlipEverything** [comment]
You have to delete the ```composer.lock``` file in order to correctly reinstall the whole vendor library.

You can verify the installation of the libraries with commands like this:
```sh
composer show
composer show vlucas/spot2
```

You can clear the local cache:
```sh
composer clear-cache
```

https://getcomposer.org/doc/03-cli.md

Maybe you specified the wrong spot version in your ```composer.json``` file. If you want the latest commit you can do this:

```json
"require": {
        "vlucas/spot2": "dev-master"
}
```

**Comment by marcelloh** [comment]
So I did and now I've got this message (never seen it before)
```
  - Removing vlucas/spot2 (v2.2.0)
  - Installing vlucas/spot2 (dev-master 4abb1bd)
    Cloning 4abb1bd1ef13741c38fc56f7f3d634b779b19eef
    Failed to download vlucas/spot2 from source: Failed to clone https://github.com/vlucas/spot2.git, git was not found, check that it is installed and in your PATH env.
```

**Comment by tuupola** [comment]
Make sure you have `git` binary in you `PATH`.

**Comment by tuupola** [comment]
Assuming this has been solved.
