### ISSUE TITLE
Bug using set{FieldCamelCase} with DateTimeType

### ISSUE THREAD

**Issue by sojimaxi** [spotorm/spot2#245]
A little bug should it self while developing my current app and its due to the autoloaded "set{FieldCamelCase}".
I think there should be an option to toggle enable or disable on this feature similar to validate.
```php
abstract class BaseModel extends \Spot\Entity
{
 public static function events(EventEmitter $eventEmitter)
    {
        $eventEmitter->on('beforeSave',function (EntityInterface $entity, MapperInterface $mapper){
            $entity->setCreatedAt();
        });
    }
    public function setCreatedAt() {
        $this->created_at = new DateTime;
     }
}

class ObjectModel extends BaseModel
{
    ...
    public static function fields()
    {
        return [
             ...
            'created_at' => ['type' => 'datetime']
        ];
    }
    ...
}
```
This make `DBAL` produce an error `Call to undefined method App\\Object::format()` since the value passed to
 `Doctrine\\DBAL\\Types\\DateTimeType->convertToDatabaseValue` was an object instead of string.

This bug goes away if I rename the setCreatedAt method to something else.

**Comment by FlipEverything** [comment]
The preferred way of initializing the DateTime field is this:

```php
class ObjectModel extends BaseModel
{
    ...
    public static function fields()
    {
        return [
             ...
            'created_at' => ['type' => 'datetime', 'value' => new \DateTime()]
        ];
    }
    ...
}
```

To be honest your solution is pretty pointless and slow.

**Comment by willemwollebrants** [comment]
"It's not a bug, it's a feature™" 

The set{FieldCamelCase} methods are indeed somewhat reserved for setters. Since your getCreatedAt-method returns nothing, I was expecting created_at to be null to be honest. 

You have options:
- use @FlipEverything 's solution, but know that this sets the datetime when the entity is built, not saved so there might be a few milliseconds difference (probably doesn't matter in daily life, but still)
- have setCreatedAt() return a new DateTime()
- just use `$entity->created_at = new DateTime()` in the event handler
- choose a different name for the setCreatedAt function 
- or even set created_at in the __construct() method 

What @FlipEverything suggested is probably the easiest, most elegant way.

**Comment by sojimaxi** [comment]
Thanks.  @willemwollebrants I the problem was setCreatedAt not returning a DateTime object. I knew it was a feature and only thought if it could be toggled.  Just wondering why you said created_at should be null.
